### ISSUE TITLE
Error in proposal submission

### ISSUE THREAD

**Issue by twakeford** [ubiquitypress/rua#357]
After clicking the submit button on a proposal form the user is faced with a screen that suggests all elements need more info/errors in the data.

After c.5sec the screen then changes to show that the submission has been completed successfully.

This has been replicated by myself and Andy = bug needs fixing

**Comment by IoannisCleary** [comment]
@twakeford  it's not a bug, the message does not appear because of form validation. the message is a reminder  of the required field, if you click on them it scrolls down to the field. This is useful when the page does not redirect. it was a fix for an older issue about text areas that used the jqte editor where the message 'this field is required' was shown at the top of the page and not where the field was.

**Comment by twakeford** [comment]
@IoannisCleary but it appears even when all of the required fields are completed. If fields are still required then fine, but the page is very confusing as it is a) because it looks like there are errors when there are not and b) because the page switches after a small amount of time, which is really odd. If there are not outstanding mandatory fields then it should go straight to the submission completed screen.

**Comment by IoannisCleary** [comment]
@twakeford It will appear every time. I know it's confusing. Since the missing text area field doesn't refresh the page, the error cannot be caught through validation so this was one of the solutions that could work. Unless we remove text editors

**Comment by ajrbyers** [comment]
@IoannisCleary im taking over this issue!

**Comment by IoannisCleary** [comment]
solved in #440
